spring:
  jpa:
    database-platform:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url:
    jdbcUrl: jdbc:h2:mem:pokermanager;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false
